language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: srinandank
  password:
    secure: pf95sie2DZ4zgfJWBb2xPQkbpZddVvJKwlnh4PQrtZQJ1Zrj2QvITLik7x/jPpiXVWwqR/X2U0eM8j98JOOubJKIiFeVPAF3zg9KGy5/NLE5HBteyKX5HtMRzNgk5PRckqstOTHlupmhK/K7Jji4TzmN2889E3r+tZ4qewvDqbtSIzQ/n7LdiRTDOf/FMGIOKiVo+aleb61kFszVcLgy5nn1zh8JJ0V20Awq12pEIRPJSFzZoWSrFQlW50vcacJnJokjJfMes+4K3HjNKTDLGcNG+bSTdnxVWzN49sRydvo6izPGY1Sl6WYFEKRGdr/gOPbz2renicBRXtS9jfTM/nWU5w03GOHRsuKCKLAwOxWnBUf7rAIi6cMBftHxcMOvJRLY7iilOkuaYvrRn77EeVYy11CaAdq/lRC9BkIPqK3t8101NDoTSver+V24Sp/vee+6Qk5jL9i6uZdkDYvKNVFomMGysIngd8txHG203H3pm0xwstVhwi1JsK96P1Bd06dc/PnE1EkqBIOUcun2Pe6JXYR2H28LDDfIlyVYMO9u7aarCWCGRKPS0EFIwwRldn9E5R3KRE3qRmKnF2nhxcnthZ6NAqUb9hd1l0x8LdYPe/+0byh+jg2n25CBoYUdVwXsVvtWVdqFi2H8w2rclr62Wbl7ncahtYHJ4mH+ENQ=
  on:
    tags: true
    repo: srinandank/gensetpy
    python: 3.8
